# Generated by Django 5.2.12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Event",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("bride_name", models.CharField(max_length=255)),
                ("groom_name", models.CharField(max_length=255)),
                ("wedding_date", models.DateField()),
                ("bride_image", models.ImageField(blank=True, null=True, upload_to="events/")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
