# Generated by Django 5.2.12 on 2026-04-03 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_bride'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='max_photos',
            field=models.PositiveIntegerField(blank=True, help_text='Maximum number of guest photos for this event; leave empty for no limit.', null=True),
        ),
    ]
