# Generated by Django 5.2.12 on 2026-03-17 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='captured_by',
            field=models.CharField(blank=True, help_text='Name of the person operating the camera.', max_length=100),
        ),
        migrations.AddField(
            model_name='photo',
            name='subject_names',
            field=models.CharField(blank=True, help_text='Comma-separated names of people in the image (e.g. guest, bride).', max_length=250),
        ),
    ]
