# Generated by Django 5.2.12 on 2026-04-04 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0002_photo_captured_by_photo_subject_names'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='is_approved',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='photo',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='photo',
            name='is_hidden',
            field=models.BooleanField(default=False),
        ),
    ]
