# Generated by Django 5.2.12 on 2026-04-04 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='KioskSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_title', models.CharField(blank=True, default='', max_length=255)),
                ('logo_url', models.URLField(blank=True, default='')),
                ('default_template', models.CharField(blank=True, default='classic', max_length=64)),
                ('default_background', models.CharField(blank=True, default='elegant', max_length=64)),
            ],
            options={
                'verbose_name_plural': 'Kiosk settings',
            },
        ),
    ]
